# Generated by Django 3.0.5 on 2020-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='trackID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PatrolIncident',
        ),
    ]
