version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: mysql:5.7
    ports:
      - '5432:3306'
    environment:
       MYSQL_DATABASE: 'CRITr'
       MYSQL_USER: 'admin_'
       MYSQL_PASSWORD: 'yG32fa*2Pe%Cr'
  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/CRITr
    expose:
      - "80"
    depends_on:
      - db
