# Generated by Django 3.0 on 2019-12-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
