# Generated by Django 3.0 on 2019-12-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_incident_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
