# Generated by Django 3.0 on 2020-01-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='trackID',
            field=models.IntegerField(default=0),
        ),
    ]
