# Generated by Django 3.0 on 2020-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_track_trackid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='trackID',
            field=models.IntegerField(),
        ),
    ]
